# Generated by Django 3.1.3 on 2020-11-19 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManager', '0002_bookbranchcopies_branch_department_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookbranchcopies',
            options={'verbose_name': "Branch's Copies", 'verbose_name_plural': 'Branch Copies'},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'branch', 'verbose_name_plural': 'branches'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
    ]
