# Generated by Django 3.1.3 on 2020-11-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManager', '0008_auto_20201119_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='num_pages',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='postal_code',
            field=models.PositiveIntegerField(blank=True, default=44444, null=True),
        ),
    ]
