# Generated by Django 3.1.3 on 2020-11-19 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManager', '0012_auto_20201119_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
    ]
